### ISSUE TITLE
audio.soloudaudio imports sdl and conflicts with Raylib

### ISSUE THREAD

**Issue by Kerntrick** [bmx-ng/audio.mod#2]
Not sure if it's worthy of attention, but importing audio.soloudaudio creates multiple definitions of some 3dMath and matrix functions  
`
Import ray.lib

Import ray.GUI

Import audio.soloudaudio
`

`C:/Dev/Lang/BmaxNG/mod/ray.mod/lib.mod/lib.release.win32.x64.a(lrs_core.c.release.win32.x64.o):core.c:(.text+0x91a0): multiple definition of `MatrixIdentity'
C:/Dev/Lang/BmaxNG/mod/ray.mod/lib.mod/lib.release.win32.x64.a(lrs_core.c.release.win32.x64.o):core.c:(.text+0x9950): multiple definition of `MatrixMultiply'
C:/Dev/Lang/BmaxNG/mod/sdl.mod/sdl.mod/sdl.release.win32.x64.a(Ssr_SDL_d3dmath.c.release.win32.x64.o):SDL_d3dmath.c:(.text+0x90): first defined here
collect2.exe: error: ld returned 1 exit status
Build Error: Failed to link `

**Comment by woollybah** [comment]
Yes, that's not going to mix well together :)

raylib uses glfw as its window/context manager, So adding SDL to that mix (which the audio mod uses manage the audio drivers) is going to be an issue.

raylib does have its own audio stuff, which I have yet to implement.

I envisage the raylib stuff as being pretty much standalone in regards to mixing with some other modules - like SDL - since they are both attempting to accomplish similar things.

raylib also doesn't support loading from incbin, which is unfortunate. maybe in the future this will change, of course.

**Comment by woollybah** [comment]
I've implemented `ray.audio` now, and examples, which should help for now.

I see soloud has some new backends available, including miniaudio - so, we may be able to have two backends configured for soloud at some point - sdl and miniaudio - allowing the use of `audio.mod` with raylib (in place of using the `ray.audio` module).

**Comment by woollybah** [comment]
You can now use:
```blitzmax
Import audio.SoloudAudioMiniAudio

SetAudioDriver("SoLoud")
```
to select the new miniaudio driver.
